### ISSUE TITLE
Length detection highlighting disappears when scrolling

### ISSUE THREAD

**Issue by rec0de** [luelista/pre_workbench#26]
Hi!

The length highlighting in the hex view is super neat, but when selecting the length field of a long-ish packet that does not fit on the screen completely, the highlighting disappears when scrolling down to find the end, even though the length field stays selected.

(tested on the pypi release)

**Comment by luelista** [comment]
Problem is that highlightMatch exits early as soon as it tries to highlight a byte that is outside the viewport.

https://github.com/luelista/pre_workbench/blob/main/pre_workbench/controls/hexview_selheur.py#L76

We either need to fix highlightMatch so it skips to the viewport, or call it with only the visible range. First is probably the better solution

**Comment by luelista** [comment]
fixed
