### ISSUE TITLE
re-implement "Data Inspector" in HexView

### ISSUE THREAD

**Issue by luelista** [luelista/pre_workbench#4]
display selected bytes as various int/uint types

![image](https://user-images.githubusercontent.com/388142/67376944-3dee6580-f585-11e9-89c9-e83aceae7d11.png)

**Comment by max-weller** [comment]
also as: color, IP address, 

also: calculate checksums (various CRC), hashes

(maybe some transformations like base64-decode, unzip, etc??)

**Comment by max-weller** [comment]
which inspections to display should be configurable by user, also possibility to add custom python expressions which are eval'd for the selection
